package cli

import (
	"bytes"
	"context"
	"testing"
)

type cancelWriter struct {
	buffer bytes.Buffer
	cancel context.CancelFunc
}

func (w *cancelWriter) Write(data []byte) (int, error) {
	n, err := w.buffer.Write(data)
	w.cancel()
	return n, err
}

func TestExecuteHelpAndVersionUseStdout(t *testing.T) {
	tests := []struct {
		name string
		args []string
		want []string
	}{
		{name: "help", args: []string{"--help"}, want: []string{"Usage:", "remainder [flags]"}},
		{name: "version", args: []string{"--version"}, want: []string{"remainder v0.1.0 (github.com/douglasjarquin/remainder)"}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var stdout, stderr bytes.Buffer
			code := Execute(context.Background(), tt.args, &stdout, &stderr, "v0.1.0")
			if code != 0 {
				t.Fatalf("Execute() exit code = %d, want 0", code)
			}
			if stdout.String() == "" {
				t.Fatal("stdout is empty")
			}
			for _, want := range tt.want {
				if !bytes.Contains(stdout.Bytes(), []byte(want)) {
					t.Fatalf("stdout = %q, want substring %q", stdout.String(), want)
				}
			}
			if tt.name == "help" && bytes.Contains(stdout.Bytes(), []byte("completion")) {
				t.Fatalf("stdout = %q, want autogenerated completion disabled", stdout.String())
			}
			if stderr.Len() != 0 {
				t.Fatalf("stderr = %q, want empty", stderr.String())
			}
		})
	}
}

func TestExecuteRejectsUnknownFlag(t *testing.T) {
	var stdout, stderr bytes.Buffer
	code := Execute(context.Background(), []string{"--unknown"}, &stdout, &stderr, "v0.1.0")
	if code == 0 {
		t.Fatal("Execute() exit code = 0, want failure")
	}
	if stderr.Len() == 0 {
		t.Fatal("stderr is empty, want an actionable error")
	}
	if bytes.Contains(stderr.Bytes(), []byte("Usage:")) {
		t.Fatalf("stderr = %q, want no automatic usage", stderr.String())
	}
}

func TestExecuteRejectsKeychainPromptForNonCursorProvider(t *testing.T) {
	adapter := &fixtureAdapter{observation: benchmarkObservation()}
	var stdout, stderr bytes.Buffer

	code := executeWithAdapter(t.Context(), []string{"--provider=codex", "--allow-keychain-prompt"}, &stdout, &stderr, "test", adapter)

	if code != 2 || adapter.calls != 0 || stdout.Len() != 0 || !bytes.Contains(stderr.Bytes(), []byte("--allow-keychain-prompt requires --provider cursor or --all")) {
		t.Fatalf("code=%d calls=%d stdout=%q stderr=%q", code, adapter.calls, stdout.String(), stderr.String())
	}
}

func TestExecuteRequiresProviderSelectionForQuota(t *testing.T) {
	var stdout, stderr bytes.Buffer
	code := Execute(context.Background(), nil, &stdout, &stderr, "v0.1.0")
	if code == 0 {
		t.Fatal("Execute() exit code = 0, want unavailable-provider failure")
	}
	if !bytes.Contains(stderr.Bytes(), []byte("quota is unavailable; select a supported provider")) {
		t.Fatalf("stderr = %q, want unavailable-provider message", stderr.String())
	}
	if stdout.Len() != 0 {
		t.Fatalf("stdout = %q, want empty", stdout.String())
	}
	if bytes.Contains(stderr.Bytes(), []byte("Usage:")) {
		t.Fatalf("stderr = %q, want no automatic usage", stderr.String())
	}
}

func TestExecuteReturnsInterruptCodeWhenContextIsCanceled(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	var stdout, stderr bytes.Buffer
	code := Execute(ctx, []string{"--help"}, &stdout, &stderr, "v0.1.0")
	if code != 130 {
		t.Fatalf("Execute() exit code = %d, want 130", code)
	}
	if !bytes.Contains(stderr.Bytes(), []byte("interrupted")) {
		t.Fatalf("stderr = %q, want interrupt message", stderr.String())
	}
}

func TestExecuteReturnsInterruptCodeWhenContextIsCanceledDuringHelp(t *testing.T) {
	ctx, cancel := context.WithCancel(context.Background())
	stdout := &cancelWriter{cancel: cancel}
	var stderr bytes.Buffer

	code := Execute(ctx, []string{"--help"}, stdout, &stderr, "v0.1.0")
	if code != 130 {
		t.Fatalf("Execute() exit code = %d, want 130", code)
	}
	if !bytes.Contains(stderr.Bytes(), []byte("interrupted")) {
		t.Fatalf("stderr = %q, want interrupt message", stderr.String())
	}
}

func TestExecuteBuildsFreshCommandInstances(t *testing.T) {
	var firstOut, firstErr bytes.Buffer
	if code := Execute(context.Background(), []string{"--help"}, &firstOut, &firstErr, "v0.1.0"); code != 0 {
		t.Fatalf("help exit code = %d, want 0", code)
	}

	var secondOut, secondErr bytes.Buffer
	code := Execute(context.Background(), nil, &secondOut, &secondErr, "v0.1.0")
	if code != 1 {
		t.Fatalf("unavailable exit code = %d, want 1", code)
	}
	if secondOut.Len() != 0 {
		t.Fatalf("second stdout = %q, want empty", secondOut.String())
	}
}

func TestExecuteRejectsUnknownCommandWithoutUsage(t *testing.T) {
	var stdout, stderr bytes.Buffer
	code := Execute(context.Background(), []string{"quota"}, &stdout, &stderr, "v0.1.0")
	if code != 2 {
		t.Fatalf("Execute() exit code = %d, want 2", code)
	}
	if !bytes.Contains(stderr.Bytes(), []byte("unknown command")) {
		t.Fatalf("stderr = %q, want unknown-command diagnostic", stderr.String())
	}
	if bytes.Contains(stderr.Bytes(), []byte("Usage:")) {
		t.Fatalf("stderr = %q, want no automatic usage", stderr.String())
	}
}
